AllCops:
  Exclude:
    - 'Gemfile.lock'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
