version: '3.7'

services:
  db:
    image: postgres:10.12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"